sudo: required
language: node_js
node_js:
  - '10.9.0'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

git:
  depth: 1

cache:
  yarn: true
  directories:
    - ./node_modules

before_install:
  - set -e
  - export NG_CLI_ANALYTICS=ci
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

env:
  - TASK=build
  - TASK=test
  - TASK=lint
  - TASK=site:build

script:
  - npm run $TASK
  - |
    if [ "$TASK" = "test" ]; then
      cat ./coverage/lcov.info | ./node_modules/.bin/codecov
    fi
